export const TOGGLE_FAVOURITE = "CONTENT/TOGGLE_FAVOURITE";
export const SET_MOVIES = "CONTENT/SET_MOVIES";
export const SET_MOVIES_SUCCESS = "CONTENT/SET_MOVIES_SUCCESS";
export const SET_MOVIES_ERROR = "CONTENT/SET_MOVIES_ERROR";
